README
======

WebkitFLTK is a port of Webkit to FLTK 1.3.

As it's intended for use in the Fifth browser, some of the HTML functionality
has corresponding changes.

It very likely won't be upstreamed, as the Webkit community has (rightfully)
some strict requirements for ports that we can't fill (3 full-time people, etc.).

Building
--------

You can try to build using the upstream Webkit cmake scripts, or the hacked-up
plain makefiles included herein.

The cmake system did not work for us, which is the reason for the makefiles.

----
make -C Source/WTF/wtf
make -C Source/JavaScriptCore gen
make -C Source/JavaScriptCore
make -C Source/WebCore
make -C Source/WebKit/fltk

# Optionally
make -C Source/WebKit/fltk install
----

Notes
-----

GCC 4.7.3 minimum. 4.7 series is in theory enough, but .0-.2 had a C++11 bug.
4.8.3 tested.

On debug vs release
-------------------

We don't like to hide functionality behind magic, so "release" and "debug" are
fully controlled by your CXXFLAGS.

release:: A build without -g and with -DNDEBUG, ie no asserts. Requires about 500mb
		space.
debug:: A built with -g and without -DNDEBUG, both asserts and debug symbols.
	Requires around 10gb space.
asserts only:: Without -g, without -DNDEBUG. Requires about 2gb space.

The asserts are helpful when debugging crashes, while taking much less space
than a full debug build. They aren't that useful in normal use, because almost
every other site blows up then.
